{{- if .Values.daemon -}}
  {{- if .Values.clean -}}
   {{- fail "Cannot clean in daemon mode" -}}
  {{- end -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exposecontroller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "exposecontroller.name" . }}
    helm.sh/chart: {{ include "exposecontroller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
  {{- range $key, $val := .Values.annotations }}
    {{ $key | quote }}: {{ $val | quote }}
  {{- end }}
  {{- range $key, $val := .Values.Annotations }}
    {{ $key | quote }}: {{ $val | quote }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "exposecontroller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "exposecontroller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: exposecontroller
        image: "{{ .Values.image.repository }}:{{ default .Chart.Version .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /exposecontroller
        - --daemon
        {{- if kindIs "slice" .Values.watchNamespaces }}
        - --watch-namespaces
        - {{ .Values.watchNamespaces | join "," | quote }}
        {{- else if not (kindIs "invalid" .Values.watchNamespaces) }}
        - --watch-namespaces
        - {{ .Values.watchNamespaces | quote }}
        {{- else if or .Values.watchCurrentNamespace (kindIs "invalid" .Values.watchCurrentNamespace) }}
        - --watch-current-namespace=true
        {{- else }}
        - --watch-current-namespace=false
        {{- end }}
        {{- range (coalesce .Values.args .Values.Args) }}
        - {{ . | quote }}
        {{- end }}
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: health
          containerPort: 10254
        readinessProbe:
          httpGet:
            path: /healthz
            port: health
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ include "exposecontroller.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
