{{- if not .Values.daemon -}}

  {{- $current := .Values.watchCurrentNamespace -}}
  {{- if kindIs "invalid" .Values.watchCurrentNamespace -}}
    {{- $current = kindIs "invalid" .Values.watchNamespaces -}}
  {{- end -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "exposecontroller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "exposecontroller.name" . }}
    helm.sh/chart: {{ include "exposecontroller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
  {{- range $key, $val := .Values.annotations }}
    {{ $key | quote }}: {{ $val | quote }}
  {{- end }}
  {{- range $key, $val := .Values.Annotations }}
    {{ $key | quote }}: {{ $val | quote }}
  {{- end }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "exposecontroller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: exposecontroller
        image: "{{ .Values.image.repository }}:{{ default .Chart.Version .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /exposecontroller
        {{- if $current }}
        - --watch-current-namespace
        {{- else if kindIs "slice" .Values.watchNamespaces }}
        - --watch-namespaces
        - {{ .Values.watchNamespaces | join "," | quote }}
        {{- else }}
        - --watch-namespaces
        - {{ default "" .Values.watchNamespaces | quote }}
        {{- end }}
        {{- if .Values.clean }}
        - --clean
        {{- end }}
        {{- range (coalesce .Values.args .Values.Args) }}
        - {{ . | quote }}
        {{- end }}
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Never
      serviceAccountName: {{ include "exposecontroller.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}